idf_component_register(
    SRCS
        "main.c"
        "board/board_display.c"
        "board/board_buttons.c"
        "board/board_audio.c"
        "ui/friend_ui.c"
        "ui/friend_media.c"
        "ui/friend_media_store.c"
        "ui/friend_gif.c"
        "ui/friend_subtitle.c"
        "ui/font_vietnamese_16.c"
        "ai/friend_ai.c"
        "network/friend_wifi.c"
        "network/friend_http.c"
        "network/friend_wifi_store.c"
    INCLUDE_DIRS "."
    REQUIRES
        esp_http_server
        esp_wifi
        esp_netif
        nvs_flash
        esp_driver_spi
        esp_driver_gpio
        esp_driver_i2s
        esp_lcd
        esp_timer
        esp_partition
        esp_http_client
        json
        mbedtls
    EMBED_TXTFILES
        "web/index.html"
        "web/style.css"
        "web/app.js"
        "web/home.html"
        "web/home.js"
        "web/gif-resize.js"
)
